### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by pinkasey** [Workiva/dependency_validator#76]
It would like to be able to use this plugin as part of CI/CD.
mainly -
if it detects an unused package, it should fail the build.
Right now I see that it only prints to the cli.

So if you could add a flag like `--fail-on-unused-package` or something,
and this flag would cause the execution to terminate with an error code -
that would be enough for us to use this in CI/CD -
simply run `flutter pub run dependency_validator --fail-on-unused-package`, and if it fails - the build fails.

WDYT?

**Comment by evanweible-wf** [comment]
Hey @pinkasey, sorry for the delay in responding. It should return a non-zero exit code for any of the following findings:

- Missing: When a dependency is used in the package but not declared in the pubspec.yaml
- Under-promoted: When a dependency is used within lib/ but only declared as a dev_dependency.
- Over-promoted: When a dependency is only used outside lib/ but declared as a dependency.
- Unused: When a dependency is not used in the package but declared in the pubspec.yaml.

(The only exceptions to this are for packages that provide executables or auto-applied builders, since we assume those to be used for convenience. The tool should make a note of those things, though.)

We do list those things in the readme, but it isn't explicitly stated that all of these should result in an non-zero exit code. I agree that would be a good note to add!

Also FYI we just released a bug fix (#78) because we were previously returning a zero exit code if the deprecated command-line arguments from v2 were used. That should now properly return a non-zero exit code, too.
